const templates = [
    { id: 'T01', active: true, name: 'Basic', inverted: false },
    { id: 'T02', active: true, name: 'Basic (Black Logo)', inverted: false, logoVariation: true },
    { id: 'T03', active: true, name: 'Grey', inverted: true, colored: 'grey' },
    { id: 'T04', active: true, name: 'Black', inverted: true, colored: 'black' },
    { id: 'T05', active: true, name: 'Blue', inverted: true, colored: 'blue' },
    { id: 'T06', active: false, name: 'Blue', inverted: true, colored: 'blue', colorVariation: 'secondary' },
    { id: 'T07', active: false, name: 'Blue', inverted: true, colored: 'blue', colorVariation: 'tertiary' },
    { id: 'T08', active: false, name: 'Teal', inverted: true, colored: 'teal' },
    { id: 'T09', active: false, name: 'Teal', inverted: true, colored: 'teal', colorVariation: 'secondary' },
    { id: 'T10', active: false, name: 'Teal', inverted: true, colored: 'teal', colorVariation: 'tertiary' },
    { id: 'T11', active: false, name: 'Violet', inverted: true, colored: 'violet' },
    { id: 'T12', active: false, name: 'Violet', inverted: true, colored: 'violet', colorVariation: 'secondary' },
    { id: 'T13', active: false, name: 'Violet', inverted: true, colored: 'violet', colorVariation: 'tertiary' },
    { id: 'T14', active: false, name: 'Purple', inverted: true, colored: 'purple' },
    { id: 'T15', active: false, name: 'Purple', inverted: true, colored: 'purple', colorVariation: 'secondary' },
    { id: 'T16', active: false, name: 'Purple', inverted: true, colored: 'purple', colorVariation: 'tertiary' },
    { id: 'T17', active: false, name: 'Pink', inverted: true, colored: 'pink' },
    { id: 'T18', active: false, name: 'Pink', inverted: true, colored: 'pink', colorVariation: 'secondary' },
    { id: 'T19', active: false, name: 'Pink', inverted: true, colored: 'pink', colorVariation: 'tertiary' },
    { id: 'T20', active: false, name: 'Brown', inverted: true, colored: 'brown' },
    { id: 'T21', active: false, name: 'Brown', inverted: true, colored: 'brown', colorVariation: 'secondary' },
    { id: 'T22', active: false, name: 'Brown', inverted: true, colored: 'brown', colorVariation: 'tertiary' },
    { id: 'T23', active: false, name: 'Red', inverted: true, colored: 'red' },
    { id: 'T24', active: false, name: 'Red', inverted: true, colored: 'red', colorVariation: 'secondary' },
    { id: 'T25', active: false, name: 'Red', inverted: true, colored: 'red', colorVariation: 'tertiary' },
    { id: 'T26', active: false, name: 'Orange', inverted: true, colored: 'orange' },
    { id: 'T27', active: false, name: 'Orange', inverted: true, colored: 'orange', colorVariation: 'secondary' },
    { id: 'T28', active: false, name: 'Orange', inverted: true, colored: 'orange', colorVariation: 'tertiary' },
    { id: 'T29', active: false, name: 'Yellow', inverted: true, colored: 'yellow' },
    { id: 'T30', active: false, name: 'Yellow', inverted: true, colored: 'yellow', colorVariation: 'secondary' },
    { id: 'T31', active: false, name: 'Yellow', inverted: true, colored: 'yellow', colorVariation: 'tertiary' },
    { id: 'T32', active: false, name: 'Olive', inverted: true, colored: 'olive' },
    { id: 'T33', active: false, name: 'Olive', inverted: true, colored: 'olive', colorVariation: 'secondary' },
    { id: 'T34', active: false, name: 'Olive', inverted: true, colored: 'olive', colorVariation: 'tertiary' },
    { id: 'T35', active: false, name: 'Green', inverted: true, colored: 'green' },
    { id: 'T36', active: false, name: 'Green', inverted: true, colored: 'green', colorVariation: 'secondary' },
    { id: 'T37', active: false, name: 'Green', inverted: true, colored: 'green', colorVariation: 'tertiary' },
]

export {
    templates
}